{% set name = "DataLabSimpleClient" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cdlclient/cdlclient-{{ version }}.tar.gz
  sha256: e203c703757b278965481883c801e2b49246e2cb9826d7f0e42ae4472a4a8599

build:
  number: 0

outputs:
  - name: {{ name|lower }}
    build:
      noarch: python
      script: python -m pip install . -vv --no-deps --no-build-isolation
      entry_points:
        - cdlclient-tests = cdlclient.tests:run
    requirements:
      host:
        - python {{ python_min }}
        - setuptools
        - pip
      run:
        - python >={{ python_min }}
        - numpy >=1.21
        - guidata >=3.5
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - cdlclient
      commands:
        - pip check
  - name: cdlclient
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name|lower, exact=True) }}
    test:
      requires:
        - python {{ python_min }}
      imports:
        - cdlclient

about:
  summary: Python library providing a simple remote client to DataLab (CDL) application
  home: https://github.com/DataLab-Platform/DataLabSimpleClient/
  doc_url: https://cdlclient.readthedocs.io/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PierreRaybaut
